# Workloads information - azure
# Ref: https://etcd.io/docs/current/op-guide/configuration/ + https://github.com/bitnami/charts/tree/master/bitnami/etcd + https://etcd.io/docs/v3.4.0/op-guide/container/ and comments at end!
# Example of escaping to the value to be parsed inside container: ``$``(MY_POD_IP``)
# Notes: Using internal Docker addresses since etcd refuses the client or peer URLs when trying to bind to the host name or IP
# Ingress: TCP: --set tcp.[external-port]="[namespace]/[service]:[port]"
# For localhost, notice that the etcd type is set to NodePort
---
globalVariables:
  # TO-SET: set domain below, like yrn42.com
  # websiteDomain:         "yrn42website-domain"
  websiteDomain:         "yrn42.com"
  # TO-SET: set site address below, like www.yrn42.com
  # websiteHost:           "www.yrn42website-domain"
  # see: https://letsencrypt.org/docs/certificates-for-localhost/
  websiteHost:           "localhost"
  websiteTlsSecret:      "website-tls-secret"
  certManagerIssuerEmail: "certificates@cloudtalk.app"
  _registryLocation:     '$($([Environment]::GetEnvironmentVariable("${env:registryName}.registryLocation")) -replace ''.azurecr.io'','''')'
  dockerServer:          "${env:_registryLocation}.azurecr.io"
  dockerUsername:        "$(az acr credential show -n ${env:_registryLocation} --query username)"
  dockerPassword:        "$(az acr credential show -n ${env:_registryLocation} --query passwords[0].value)"
  ingressClass:          "nginx"
  _namespace001:         "${env:project}-${env:runId}-001"
  _namespace002:         "${env:project}-${env:runId}-002"
  _namespace003:         "${env:project}-${env:runId}-003"
  _frontend001:          $([Environment]::GetEnvironmentVariable("${env:runTag}-${env:project}-${env:runId}-001.hostname"))
  _frontend002:          $([Environment]::GetEnvironmentVariable("${env:runTag}-${env:project}-${env:runId}-002.hostname"))
  _frontend003:          $([Environment]::GetEnvironmentVariable("${env:runTag}-${env:project}-${env:runId}-003.hostname"))
  etcdPassword:          "yurunaDemo"
  etcdPrefix:            "etcd"
  # https://etcd.io/docs/v3.5/op-guide/clustering/
  # Avoid collisions: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
  etcdDiscovery:         "$(wget -q -O - https://discovery.etcd.io/new?size=3 2>null)"
  etcdAddress001:        $([Environment]::GetEnvironmentVariable("${env:runTag}-${env:project}-${env:runId}-001.frontendIp"))
  etcdHeadless001:       '${env:etcdPrefix}001-0.${env:etcdPrefix}001-headless.${env:_namespace001}.svc.cluster.local'
  etcdPortClient001:     "42001"
  etcdPortPeer001:       "43001"
  etcdAddress002:        $([Environment]::GetEnvironmentVariable("${env:runTag}-${env:project}-${env:runId}-002.frontendIp"))
  etcdHeadless002:       '${env:etcdPrefix}002-0.${env:etcdPrefix}002-headless.${env:_namespace002}.svc.cluster.local'
  etcdPortClient002:     "42002"
  etcdPortPeer002:       "43002"
  etcdAddress003:        $([Environment]::GetEnvironmentVariable("${env:runTag}-${env:project}-${env:runId}-003.frontendIp"))
  etcdHeadless003:       '${env:etcdPrefix}003-0.${env:etcdPrefix}003-headless.${env:_namespace003}.svc.cluster.local'
  etcdPortClient003:     "42003"
  etcdPortPeer003:       "43003"
  etcdCluster:           ${env:etcdPrefix}001=http://${env:etcdAddress001}:${env:etcdPortPeer001}\,${env:etcdPrefix}002=http://${env:etcdAddress002}:${env:etcdPortPeer002}\,${env:etcdPrefix}003=http://${env:etcdAddress003}:${env:etcdPortPeer003}
  etcdClusterToken:      "nossila"  
  waitTimeout:           "2m"

workloads:
# Cleanup
# Always delete everything first, so that no references are created to existing resources previously available
- context: "${env:runTag}-${env:project}-${env:runId}-001"
  variables:
    _number: "001"
    _basename: "${env:containerPrefix}${env:_number}"
    namespace: '$([Environment]::GetEnvironmentVariable("_namespace${env:_number}"))'
  deployments:
    - kubectl: "delete namespace ingress-ns --ignore-not-found=true --v=1"
    - kubectl: "delete namespace ${env:namespace} --ignore-not-found=true --v=1"
    - shell: 'Write-Information "   Cleaned ${env:contextName}"'

- context: "${env:runTag}-${env:project}-${env:runId}-002"
  variables:
    _number: "002"
    _basename: "${env:containerPrefix}${env:_number}"
    namespace: '$([Environment]::GetEnvironmentVariable("_namespace${env:_number}"))'
  deployments:
    - kubectl: "delete namespace ingress-ns --ignore-not-found=true --v=1"
    - kubectl: "delete namespace ${env:namespace} --ignore-not-found=true --v=1"
    - shell: 'Write-Information "   Cleaned ${env:contextName}"'

- context: "${env:runTag}-${env:project}-${env:runId}-003"
  variables:
    _number: "003"
    _basename: "${env:containerPrefix}${env:_number}"
    namespace: '$([Environment]::GetEnvironmentVariable("_namespace${env:_number}"))'
  deployments:
    - kubectl: "delete namespace ingress-ns --ignore-not-found=true --v=1"
    - kubectl: "delete namespace ${env:namespace} --ignore-not-found=true --v=1"
    - shell: 'Write-Information "   Cleaned ${env:contextName}"'

# Artifact creation phase

# 001
- context: "${env:runTag}-${env:project}-${env:runId}-001"
  variables:
    _number: "001"
    _basename: "${env:containerPrefix}${env:_number}"
    namespace: '$([Environment]::GetEnvironmentVariable("_namespace${env:_number}"))'
    frontendApp: "${env:_basename}-site"
    frontendPathBase: "front${env:_number}"
    backendApp: "${env:_basename}-grava"
    backendPathBase: "back${env:_number}"
    replicatedStateApp: "${env:etcdPrefix}${env:_number}"
    replicatedStatePortClient: '$([Environment]::GetEnvironmentVariable("etcdPortClient${env:_number}"))'
    replicatedStatePortPeer: '$([Environment]::GetEnvironmentVariable("etcdPortPeer${env:_number}"))'
    replicatedStateAppAddress: '$([Environment]::GetEnvironmentVariable("etcdAddress${env:_number}"))'
    replicatedStateAppHeadless: '$([Environment]::GetEnvironmentVariable("etcdHeadless${env:_number}"))'
    _endpointHost: '$([Environment]::GetEnvironmentVariable("${env:contextName}.hostname"))'
    _frontendIp: "$([Environment]::GetEnvironmentVariable(\"${env:contextName}.frontendIp\"))"
  deployments:
    - kubectl: "create namespace ${env:namespace} --v=1"
    - kubectl: "create namespace ingress-ns --v=1"
    - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
    - kubectl: "create secret docker-registry registry-credential --docker-server=${env:dockerServer} --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
    - chart: "replicator-app"
      variables:
        installName: "replicator-app-${env:runId}-${env:_number}"
    - helm: "repo add bitnami https://charts.bitnami.com/bitnami"
    - helm: "repo update"
    - helm: >
        install ${env:replicatedStateApp} bitnami/etcd
        --namespace ${env:namespace}
        --set persistence.enabled=false
        --set auth.rbac.enabled=false
        --set containerPorts.client=${env:replicatedStatePortClient}
        --set containerPorts.peer=${env:replicatedStatePortPeer}
        --set service.port=${env:replicatedStatePortClient}
        --set service.peerPort=${env:replicatedStatePortPeer}
        --set service.type=LoadBalancer
        --set extraEnvVars[0].name=ALLOW_NONE_AUTHENTICATION
        --set extraEnvVars[0].value=yes
        --set extraEnvVars[1].name=ETCD_NAME
        --set extraEnvVars[1].value=${env:replicatedStateApp}
        --set extraEnvVars[2].name=ETCD_ADVERTISE_CLIENT_URLS
        --set extraEnvVars[2].value=http://${env:replicatedStateAppAddress}:${env:replicatedStatePortClient}
        --set extraEnvVars[3].name=ETCD_LISTEN_CLIENT_URLS
        --set extraEnvVars[3].value=http://0.0.0.0:${env:replicatedStatePortClient}
        --set extraEnvVars[4].name=ETCD_INITIAL_ADVERTISE_PEER_URLS
        --set extraEnvVars[4].value=http://${env:replicatedStateAppAddress}:${env:replicatedStatePortPeer}
        --set extraEnvVars[5].name=ETCD_LISTEN_PEER_URLS
        --set extraEnvVars[5].value=http://0.0.0.0:${env:replicatedStatePortPeer}
        --set extraEnvVars[6].name=ETCD_INITIAL_CLUSTER
        --set extraEnvVars[6].value=${env:etcdCluster}
        --set extraEnvVars[7].name=ETCD_INITIAL_CLUSTER_STATE
        --set extraEnvVars[7].value=new
        --set extraEnvVars[8].name=ETCD_INITIAL_CLUSTER_TOKEN
        --set extraEnvVars[8].value=${env:etcdClusterToken}
        --debug
    - helm: "repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
    - helm: "repo update"
    - helm: >
        install nginx-ingress ingress-nginx/ingress-nginx
        --namespace ingress-ns
        --set controller.replicaCount=2
        --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux
        --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
        --set controller.service.externalTrafficPolicy="Local"
        --set controller.service.loadBalancerIP="${env:_frontendIp}"
        --set controller.admissionWebhooks.enabled=false
        --set controller.ingressClass=${env:ingressClass}
        --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="${env:project}-${env:runId}-${env:_number}"
        --set tcp.${env:replicatedStatePortClient}="${env:namespace}/${env:replicatedStateApp}:${env:replicatedStatePortClient}"
        --set tcp.${env:replicatedStatePortPeer}="${env:namespace}/${env:replicatedStateApp}:${env:replicatedStatePortPeer}"        
        # --debug
    - kubectl: "expose deployment/${env:frontendApp}"
    - kubectl: "expose deployment/${env:backendApp}"
    - shell: 'Write-Information "   Enpoint: http://${env:_endpointHost}/${env:frontendPathBase}"'

# 002
- context: "${env:runTag}-${env:project}-${env:runId}-002"
  variables:
    _number: "002"
    _basename: "${env:containerPrefix}${env:_number}"
    namespace: '$([Environment]::GetEnvironmentVariable("_namespace${env:_number}"))'
    frontendApp: "${env:_basename}-site"
    frontendPathBase: "front${env:_number}"
    backendApp: "${env:_basename}-grava"
    backendPathBase: "back${env:_number}"
    replicatedStateApp: "${env:etcdPrefix}${env:_number}"
    replicatedStatePortClient: '$([Environment]::GetEnvironmentVariable("etcdPortClient${env:_number}"))'
    replicatedStatePortPeer: '$([Environment]::GetEnvironmentVariable("etcdPortPeer${env:_number}"))'
    replicatedStateAppAddress: '$([Environment]::GetEnvironmentVariable("etcdAddress${env:_number}"))'
    replicatedStateAppHeadless: '$([Environment]::GetEnvironmentVariable("etcdHeadless${env:_number}"))'
    _endpointHost: '$([Environment]::GetEnvironmentVariable("${env:contextName}.hostname"))'
    _frontendIp: "$([Environment]::GetEnvironmentVariable(\"${env:contextName}.frontendIp\"))"
  deployments:
    - kubectl: "create namespace ${env:namespace} --v=1"
    - kubectl: "create namespace ingress-ns --v=1"
    - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
    - kubectl: "create secret docker-registry registry-credential --docker-server=${env:dockerServer} --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
    - chart: "replicator-app"
      variables:
        installName: "replicator-app-${env:runId}-${env:_number}"
    - helm: "repo add bitnami https://charts.bitnami.com/bitnami"
    - helm: "repo update"
    - helm: >
        install ${env:replicatedStateApp} bitnami/etcd
        --namespace ${env:namespace}
        --set persistence.enabled=false
        --set auth.rbac.enabled=false
        --set containerPorts.client=${env:replicatedStatePortClient}
        --set containerPorts.peer=${env:replicatedStatePortPeer}
        --set service.port=${env:replicatedStatePortClient}
        --set service.peerPort=${env:replicatedStatePortPeer}
        --set service.type=LoadBalancer
        --set extraEnvVars[0].name=ALLOW_NONE_AUTHENTICATION
        --set extraEnvVars[0].value=yes
        --set extraEnvVars[1].name=ETCD_NAME
        --set extraEnvVars[1].value=${env:replicatedStateApp}
        --set extraEnvVars[2].name=ETCD_ADVERTISE_CLIENT_URLS
        --set extraEnvVars[2].value=http://${env:replicatedStateAppAddress}:${env:replicatedStatePortClient}
        --set extraEnvVars[3].name=ETCD_LISTEN_CLIENT_URLS
        --set extraEnvVars[3].value=http://0.0.0.0:${env:replicatedStatePortClient}
        --set extraEnvVars[4].name=ETCD_INITIAL_ADVERTISE_PEER_URLS
        --set extraEnvVars[4].value=http://${env:replicatedStateAppAddress}:${env:replicatedStatePortPeer}
        --set extraEnvVars[5].name=ETCD_LISTEN_PEER_URLS
        --set extraEnvVars[5].value=http://0.0.0.0:${env:replicatedStatePortPeer}
        --set extraEnvVars[6].name=ETCD_INITIAL_CLUSTER
        --set extraEnvVars[6].value=${env:etcdCluster}
        --set extraEnvVars[7].name=ETCD_INITIAL_CLUSTER_STATE
        --set extraEnvVars[7].value=new
        --set extraEnvVars[8].name=ETCD_INITIAL_CLUSTER_TOKEN
        --set extraEnvVars[8].value=${env:etcdClusterToken}
        --debug
    - helm: "repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
    - helm: "repo update"
    - helm: >
        install nginx-ingress ingress-nginx/ingress-nginx
        --namespace ingress-ns
        --set controller.replicaCount=2
        --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux
        --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
        --set controller.service.externalTrafficPolicy="Local"
        --set controller.service.loadBalancerIP="${env:_frontendIp}"
        --set controller.admissionWebhooks.enabled=false
        --set controller.ingressClass=${env:ingressClass}
        --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="${env:project}-${env:runId}-${env:_number}"
        --set tcp.${env:replicatedStatePortClient}="${env:namespace}/${env:replicatedStateApp}:${env:replicatedStatePortClient}"
        --set tcp.${env:replicatedStatePortPeer}="${env:namespace}/${env:replicatedStateApp}:${env:replicatedStatePortPeer}"        
        # --debug
    - kubectl: "expose deployment/${env:frontendApp}"
    - kubectl: "expose deployment/${env:backendApp}"
    - shell: 'Write-Information "   Enpoint: http://${env:_endpointHost}/${env:frontendPathBase}"'

# 003
- context: "${env:runTag}-${env:project}-${env:runId}-003"
  variables:
    _number: "003"
    _basename: "${env:containerPrefix}${env:_number}"
    namespace: '$([Environment]::GetEnvironmentVariable("_namespace${env:_number}"))'
    frontendApp: "${env:_basename}-site"
    frontendPathBase: "front${env:_number}"
    backendApp: "${env:_basename}-grava"
    backendPathBase: "back${env:_number}"
    replicatedStateApp: "${env:etcdPrefix}${env:_number}"
    replicatedStatePortClient: '$([Environment]::GetEnvironmentVariable("etcdPortClient${env:_number}"))'
    replicatedStatePortPeer: '$([Environment]::GetEnvironmentVariable("etcdPortPeer${env:_number}"))'
    replicatedStateAppAddress: '$([Environment]::GetEnvironmentVariable("etcdAddress${env:_number}"))'
    replicatedStateAppHeadless: '$([Environment]::GetEnvironmentVariable("etcdHeadless${env:_number}"))'
    _endpointHost: '$([Environment]::GetEnvironmentVariable("${env:contextName}.hostname"))'
    _frontendIp: "$([Environment]::GetEnvironmentVariable(\"${env:contextName}.frontendIp\"))"
  deployments:
    - kubectl: "create namespace ${env:namespace} --v=1"
    - kubectl: "create namespace ingress-ns --v=1"
    - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
    - kubectl: "create secret docker-registry registry-credential --docker-server=${env:dockerServer} --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
    - chart: "replicator-app"
      variables:
        installName: "replicator-app-${env:runId}-${env:_number}"
    - helm: "repo add bitnami https://charts.bitnami.com/bitnami"
    - helm: "repo update"
    - helm: >
        install ${env:replicatedStateApp} bitnami/etcd
        --namespace ${env:namespace}
        --set persistence.enabled=false
        --set auth.rbac.enabled=false
        --set containerPorts.client=${env:replicatedStatePortClient}
        --set containerPorts.peer=${env:replicatedStatePortPeer}
        --set service.port=${env:replicatedStatePortClient}
        --set service.peerPort=${env:replicatedStatePortPeer}
        --set service.type=LoadBalancer
        --set extraEnvVars[0].name=ALLOW_NONE_AUTHENTICATION
        --set extraEnvVars[0].value=yes
        --set extraEnvVars[1].name=ETCD_NAME
        --set extraEnvVars[1].value=${env:replicatedStateApp}
        --set extraEnvVars[2].name=ETCD_ADVERTISE_CLIENT_URLS
        --set extraEnvVars[2].value=http://${env:replicatedStateAppAddress}:${env:replicatedStatePortClient}
        --set extraEnvVars[3].name=ETCD_LISTEN_CLIENT_URLS
        --set extraEnvVars[3].value=http://0.0.0.0:${env:replicatedStatePortClient}
        --set extraEnvVars[4].name=ETCD_INITIAL_ADVERTISE_PEER_URLS
        --set extraEnvVars[4].value=http://${env:replicatedStateAppAddress}:${env:replicatedStatePortPeer}
        --set extraEnvVars[5].name=ETCD_LISTEN_PEER_URLS
        --set extraEnvVars[5].value=http://0.0.0.0:${env:replicatedStatePortPeer}
        --set extraEnvVars[6].name=ETCD_INITIAL_CLUSTER
        --set extraEnvVars[6].value=${env:etcdCluster}
        --set extraEnvVars[7].name=ETCD_INITIAL_CLUSTER_STATE
        --set extraEnvVars[7].value=new
        --set extraEnvVars[8].name=ETCD_INITIAL_CLUSTER_TOKEN
        --set extraEnvVars[8].value=${env:etcdClusterToken}
        --debug
    - helm: "repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
    - helm: "repo update"
    - helm: >
        install nginx-ingress ingress-nginx/ingress-nginx
        --namespace ingress-ns
        --set controller.replicaCount=2
        --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux
        --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
        --set controller.service.externalTrafficPolicy="Local"
        --set controller.service.loadBalancerIP="${env:_frontendIp}"
        --set controller.admissionWebhooks.enabled=false
        --set controller.ingressClass=${env:ingressClass}
        --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="${env:project}-${env:runId}-${env:_number}"
        --set tcp.${env:replicatedStatePortClient}="${env:namespace}/${env:replicatedStateApp}:${env:replicatedStatePortClient}"
        --set tcp.${env:replicatedStatePortPeer}="${env:namespace}/${env:replicatedStateApp}:${env:replicatedStatePortPeer}"        
        # --debug
    - kubectl: "expose deployment/${env:frontendApp}"
    - kubectl: "expose deployment/${env:backendApp}"
    - shell: 'Write-Information "   Enpoint: http://${env:_endpointHost}/${env:frontendPathBase}"'
