apiVersion: v1
kind: Pod
metadata:
  name: tuning-pod
  namespace: yrn42onnxtraingpt2-namespace
spec:
  volumes:
    - name: data-dir-volume
      persistentVolumeClaim:
        claimName: data-dir-pvc
  containers:
    - name: tuning-container
      image: localhost:5000/yrn42onnxtraingpt2-prefix/tuning:latest
      imagePullPolicy: Always
      command: [ "sleep" ]
      args: [ "infinity" ]
      volumeMounts:
        - mountPath: "/mnt/storage"
          name: data-dir-volume
      resources:
        limits:
          memory: "1024Mi"
          cpu: "1000m"
