# Resources information - azure
---
globalVariables:
  namespace:             "cloudtalk"
  clusterDnsPrefix:      "cloudtalk"
  resourceGroupPrefix:   "cloudtalk"
  resourceTags:          "cloudtalk"
  registryName:          "componentsRegistry"
  # regions: az account list-locations -o table
  resourceRegion:        "westus2"
  # cluster versions: az aks get-versions --location [location] -o table
  clusterVersion:        "1.23.3"
  nodeType:              "Standard_D2_v2"
  nodeCount:             3

resources:
# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
- name:                  "defaultResourceGroup"
  template:              "azure/resource-group"
  variables:
    resourceGroup:       "${env:resourceGroupPrefix}"

- name:                  "componentsRegistry"
  template:              "azure/registry"
  variables:
    # TO-SET: registry name must be globally unique
    uniqueName:          "${env:clusterDnsPrefix}"
    resourceGroup:       "${env:resourceGroupPrefix}"

# 001 - eastus
- name:                  "rg001"
  template:              "azure/resource-group"
  variables:
    resourceGroup:       "${env:resourceGroupPrefix}001"
    resourceRegion:      "eastus"

- name:                  "${env:clusterDnsPrefix}001-azure"
  template:              "azure/aks-cluster"
  variables:
    clusterName:         "${env:clusterDnsPrefix}001-azure"
    destinationContext:  "${env:clusterDnsPrefix}001-azure"
    resourceGroup:       "${env:resourceGroupPrefix}001"
    resourceRegion:      "eastus"
    nodeResourceGroup:   "${env:resourceGroupPrefix}001-aks"

# 002 - northeurope
- name:                  "rg002"
  template:              "azure/resource-group"
  variables:
    resourceGroup:       "${env:resourceGroupPrefix}002"
    resourceRegion:      "northeurope"

- name:                  "${env:clusterDnsPrefix}002-azure"
  template:              "azure/aks-cluster"
  variables:
    clusterName:         "${env:clusterDnsPrefix}002-azure"
    destinationContext:  "${env:clusterDnsPrefix}002-azure"
    resourceGroup:       "${env:resourceGroupPrefix}002"
    resourceRegion:      "northeurope"
    nodeResourceGroup:   "${env:resourceGroupPrefix}002-aks"

# 003 - westus2
- name:                  "rg003"
  template:              "azure/resource-group"
  variables:
    resourceGroup:       "${env:resourceGroupPrefix}003"
    resourceRegion:      "westus2"

- name:                  "${env:clusterDnsPrefix}003-azure"
  template:              "azure/aks-cluster"
  variables:
    clusterName:         "${env:clusterDnsPrefix}003-azure"
    destinationContext:  "${env:clusterDnsPrefix}003-azure"
    resourceGroup:       "${env:resourceGroupPrefix}003"
    resourceRegion:      "westus2"
    nodeResourceGroup:   "${env:resourceGroupPrefix}003-aks"
