# Resources information - localhost
---
globalVariables:
  namespace:             "cloudtalk"
  clusterDnsPrefix:      "cloudtalk"
  resourceGroup:         "cloudtalk"
  resourceTags:          "cloudtalk"
  registryName:          "componentsRegistry"

resources:
# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input

# localhost registry container
- name:                  "componentsRegistry"
  template:              "localhost/registry"
  variables:

# context-copy 001
- name:                  "${env:clusterDnsPrefix}001-localhost"
  template:              "localhost/context-copy"
  variables:
    clusterName:         "${env:clusterDnsPrefix}001-localhost"
    sourceContext:       "docker-desktop"
    destinationContext:  "${env:clusterDnsPrefix}001-localhost"

# context-copy 002
- name:                  "${env:clusterDnsPrefix}002-localhost"
  template:              "localhost/context-copy"
  variables:
    clusterName:         "${env:clusterDnsPrefix}002-localhost"
    sourceContext:       "docker-desktop"
    destinationContext:  "${env:clusterDnsPrefix}002-localhost"

# context-copy 003
- name:                  "${env:clusterDnsPrefix}003-localhost"
  template:              "localhost/context-copy"
  variables:
    clusterName:         "${env:clusterDnsPrefix}003-localhost"
    sourceContext:       "docker-desktop"
    destinationContext:  "${env:clusterDnsPrefix}003-localhost"
