# Components information - localhost
---
globalVariables:
  containerPrefix:  "yrn42onnxtraingpt2-prefix"
  registryName:     "componentsRegistry"
  # Notice that the 'registryName' variable is used to find the name of another variable, requiring the dual indirection
  buildCommand: docker build --rm -f ${env:dockerfile} -t "${env:containerPrefix}/${env:project}:latest" "${env:buildPath}"
  tagCommand: docker tag "${env:containerPrefix}/${env:project}:latest" "$([Environment]::GetEnvironmentVariable("${env:registryName}.registryLocation"))/${env:containerPrefix}/${env:project}:latest"
  pushCommand: docker push "$([Environment]::GetEnvironmentVariable("${env:registryName}.registryLocation"))/${env:containerPrefix}/${env:project}:latest"
 
components:
- project: "tuning"
  buildPath: "tuning"
  variables:
    preProcessor:   "Push-Location ${env:buildPath}; ./preProcessor.ps1; Pop-Location"
    postProcessor:  "Push-Location ${env:buildPath}; ./postProcessor.ps1; Pop-Location"
- project: "dataload"
  buildPath: "dataload"
  variables:
