# Components information - localhost
---
globalVariables:
  containerPrefix:  "yrn42onnxtraingpt2-prefix"
  registryLocation: "localhost:5000"
  registryName:     "localhost"
  buildCommand:     docker build --rm -f ${env:dockerfile} -t "${env:containerPrefix}/${env:project}:latest" "${env:buildPath}"
  tagCommand:       docker tag "${env:containerPrefix}/${env:project}:latest" "${env:registryLocation}/${env:containerPrefix}/${env:project}:latest"
  pushCommand:      docker push "${env:registryLocation}/${env:containerPrefix}/${env:project}:latest"
 
components:
- project: "tuning"
  buildPath: "tuning"
  variables:
    preProcessor:   "Push-Location ${env:buildPath}; ./preProcessor.ps1; Pop-Location"
    postProcessor:  "Push-Location ${env:buildPath}; ./postProcessor.ps1; Pop-Location"
- project: "dataload"
  buildPath: "dataload"
  variables:
