# Workloads information - localhost
---
globalVariables:
  namespace:         "yrn42onnxtraingpt2-namespace"
  containerPrefix:   "yrn42onnxtraingpt2-prefix"
  registryLocation:  "localhost:5000"
  registryName:      "localhost"
  frontendIpName:    "localhost"
  frontendIpAddress: "127.0.0.1"
  dockerUsername:    "dummy"
  dockerPassword:    "dummy"

workloads:
- context: "docker-desktop"
  deployments:
  # Uninstall previous workloads: idempotent
  - kubectl: "delete namespace ${env:namespace} --v=1"
  - shell: "Start-Sleep -s 9"
  # Install dependencies
  - kubectl: "create namespace ${env:namespace} --v=1"
  - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
  # Install components
  - kubectl: "create secret docker-registry registry-credential --docker-server=http://${env:registryLocation} --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
  - chart: "tuning"
    variables:
      installName: "yrn42onnxtraingpt2-prefix-tuning"
