# Workloads information - localhost
---
globalVariables:
  namespace:         "yrn42onnxtraingpt2-ns"
  containerPrefix:   "yrn42onnxtraingpt2-prefix"
  registryName:      "componentsRegistry"
  dockerUsername:    "placeholder"
  dockerPassword:    "placeholder"

workloads:
- context: "yrn42onnxtraingpt2-context"
  deployments:
  # Uninstall previous workloads: idempotent
  - kubectl: "delete namespace ${env:namespace} --v=1"
  - shell: "Start-Sleep -s 9"
  # Install dependencies
  - kubectl: "create namespace ${env:namespace} --v=1"
  - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
  # Install components
  - kubectl: "create secret docker-registry registry-credential --docker-server=http://$([Environment]::GetEnvironmentVariable(\"${env:registryName}.registryLocation\")) --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
  - chart: "tuning"
    variables:
      installName: "yrn42onnxtraingpt2-install-tuning"
