# Components information - localhost
---
globalVariables:
  DOCKER_SCAN_SUGGEST:   "false"
  containerPrefix:       "yrn42template-prefix"
  registryName:          "componentsRegistry"
  # Notice that the 'registryName' variable is used to find the name of another variable, requiring the dual indirection
  buildCommand: docker build --rm -f ${env:dockerfile} -t "${env:containerPrefix}/${env:project}:latest" "${env:buildPath}"
  tagCommand: docker tag "${env:containerPrefix}/${env:project}:latest" "$([Environment]::GetEnvironmentVariable("${env:registryName}.registryLocation"))/${env:containerPrefix}/${env:project}:latest"
  pushCommand: docker push "$([Environment]::GetEnvironmentVariable("${env:registryName}.registryLocation"))/${env:containerPrefix}/${env:project}:latest"

components:
- project: "yrn42template"
  buildPath: "yrn42template"
  variables:
