# Resources information - localhost
---
globalVariables:
  runId:                 "$(-join ((97..122) | Get-Random -Count 6 | %{[char]$_}))"
  runTag:                "localhost"
  namespace:             "website"
  containerPrefix:       "website"
  clusterDnsPrefix:      "website-${env:runId}"
  resourceGroup:         "website"
  resourceTags:          "website-${env:runId}"
  registryName:          "componentsRegistry"

# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
resources:
- name:                  "componentsRegistry"
  template:              "localhost/registry"
  variables:
    # TO-SET: registry name must be globally unique, without dashes
    uniqueName:          "${env:namespace}${env:runId}${env:runTag}"

# localhost cluster reference
- name:                  "${env:clusterDnsPrefix}-${env:runTag}"
  template:              "localhost/context-copy"
  variables:
    clusterName:         "${env:clusterDnsPrefix}-${env:runTag}"
    sourceContext:       "docker-desktop"
    destinationContext:  "${env:clusterDnsPrefix}-${env:runTag}"
