# Workloads information - localhost
---
globalVariables:
  # TO-SET: set domain below, like yrn42.com
  # websiteDomain:         "yrn42website-domain"
  websiteDomain:         "yrn42.com"
  # TO-SET: set site address below, like www.yrn42.com
  # websiteHost:           "www.yrn42website-domain"
  # see: https://letsencrypt.org/docs/certificates-for-localhost/
  websiteHost:           "localhost"
  certManagerIssuerEmail: "certificates@yrn42.com"
  websiteTlsSecret:      "website-tls-secret"
  _registryLocation:     "$($([Environment]::GetEnvironmentVariable(\"${env:registryName}.registryLocation\")) -replace '.azurecr.io','')"
  dockerServer:          "http://${env:_registryLocation}"
  dockerUsername:        "placeholder"
  dockerPassword:        "placeholder"
  ingressClass:          "nginx"

workloads:
- context: "${env:clusterDnsPrefix}-${env:runTag}"
  variables:
    _hostname: "$([Environment]::GetEnvironmentVariable(\"${env:contextName}.hostname\"))"
    _frontendIp: "$([Environment]::GetEnvironmentVariable(\"${env:contextName}.frontendIp\"))"
  deployments:
  # Uninstall previous workloads: idempotent
  - kubectl: "delete namespace ${env:namespace} --ignore-not-found=true --v=1"
  - kubectl: "delete namespace ingress-basic --ignore-not-found=true --v=1"
  - kubectl: "delete -f https://github.com/jetstack/cert-manager/releases/download/v1.7.0/cert-manager.yaml --ignore-not-found=true --v=1"
  - kubectl: "delete clusterrole nginx-ingress-ingress-nginx --ignore-not-found=true"
  - kubectl: "delete clusterrolebinding nginx-ingress-ingress-nginx --ignore-not-found=true"
  # Install dependencies
  - kubectl: "create namespace ${env:namespace} --v=1"
  - kubectl: "create namespace ingress-basic --v=1"
  - kubectl: "label namespace ingress-basic cert-manager.io/disable-validation=true --v=1"
  - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
  - helm: "repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
  - helm: "repo update"
  # Certificate
  - helm: "repo add jetstack https://charts.jetstack.io"
  - helm: "repo update"
  - helm: >
      install cert-manager jetstack/cert-manager
      --namespace ingress-basic
      --version v1.7.0
      --set installCRDs=true
      --set nodeSelector."beta\.kubernetes\.io/os"=linux
      # --debug
  - helm: >
      install nginx-ingress ingress-nginx/ingress-nginx
      --namespace ingress-basic
      --set controller.replicaCount=2
      --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set controller.admissionWebhooks.enabled=false
      --set controller.ingressClass=${env:ingressClass}
      --set controller.service.loadBalancerIP="placeholder"
      --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="placeholder"
      # --debug
  # Install components
  - kubectl: "create secret docker-registry registry-credential --docker-server=${env:dockerServer} --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
  - shell: 'Write-Information "-- Waiting: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=90s"'
  - kubectl: "wait --for=condition=Ready pods --all --all-namespaces --timeout=90s"
  - chart: "frontend/website"
    variables:
      installName: "${env:clusterDnsPrefix}-${env:runTag}"
  - shell: "Write-Information \">> Enpoint: https://${env:websiteHost}\""
  - shell: 'Write-Information "-- Waiting: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=90s"'
  - kubectl: "wait --for=condition=Ready pods --all --all-namespaces --timeout=90s"
  # For localhost: manually create certificate
  - shell: "mkcert -install"
  - shell: "mkcert -key-file \"${env:workFolder}/website-tls.key\" -cert-file \"${env:workFolder}/website-tls.crt\" ${env:websiteDomain} \"*.${env:websiteDomain}\" localhost \"*.localhost\" 127.0.0.1 ::1 ${env:_hostname}"
  - kubectl: "create secret tls ${env:websiteTlsSecret} --key \"${env:workFolder}/website-tls.key\" --cert \"${env:workFolder}/website-tls.crt\" --namespace=${env:namespace}"
  - shell: 'Write-Information "-- Check containers started: kubectl get pods --all-namespaces"'
  - shell: "Write-Information \">>    Test: curl -k -v http://${env:_frontendIp} -H 'Host: ${env:websiteHost}'\""
