apiVersion: v2
name: yrn42peerkeys-grava
description: Grava API

type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://github.com/cncf/artwork/blob/master/projects/helm/icon/color/helm-icon-color.svg