apiVersion: v1
kind: Pod
metadata:
  name: dataview-pod
  namespace: yrn42onnxtraingpt2-namespace
spec:
  volumes:
    - name: data-dir-volume
      persistentVolumeClaim:
        claimName: data-dir-pvc
  containers:
    - name: dataview-container
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/storage"
          name: data-dir-volume
      resources:
        limits:
          memory: "256Mi"
          cpu: "100m"
