apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendApp }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backendApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendApp }}
    spec:
      containers:
      - name: grava
        image: {{ index .Values (printf "%s.registryLocation" .Values.registryName) }}/{{ .Values.containerPrefix }}/grava:latest
        imagePullPolicy: Always
        ports:
        - name: port8088
          containerPort: 8088
        resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
        env:
          - name: "pathBase"
            value: {{ (printf "/%s" .Values.backendPathBase) }}
          - name: "etcdServer"
            value: {{ (printf "http://" ) }}{{ index .Values (printf "%s.hostname" .Values.contextName) }}:{{ .Values.replicatedStatePortClient }}
          - name: "etcdPassword"
            value: {{ .Values.etcdPassword }}
      imagePullSecrets:
        - name: registry-credential
