# Resources information - localhost
---
globalVariables:
  namespace:        "yrn42template-ns"
  clusterDnsPrefix: "yrn42template-dns"
  resourceGroup:    "yrn42template-rg"
  resourceTags:     "yrn42template-tags"
  nodeCount:        1
  registryName:     "componentsRegistry"

# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
resources:
# localhost registry container
- name:             "componentsRegistry"
  template:         "localhost/registry"
  variables:

# localhost cluster reference
- name:             "yrn42template-localhost"
  template:         "localhost/context-copy"
  variables:
    clusterName:    "yrn42template-cluster"
    sourceContext:  "docker-desktop"
    destinationContext:  "yrn42template-localhost"
