# Resources information - azure
---
globalVariables:
  namespace:             "yrn42website-ns"
  clusterDnsPrefix:      "yrn42website-dns"
  resourceGroup:         "yrn42website-rg"
  # regions: az account list-locations -o table
  resourceRegion:        "westus2"
  resourceTags:          "yrn42website-tags"
  registryName:          "componentsRegistry"
  clusterVersion:        "1.20.2"
  nodeType:              "Standard_D2_v2"
  nodeCount:             3

resources:
# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
- name:                  "defaultResourceGroup"
  template:              "azure/resource-group"
  variables:

- name:                  "componentsRegistry"
  template:              "azure/registry"
  variables:
    # TO-SET: registry name must be globally unique
    uniqueName:          "yrn42registry"

# cluster reference
- name:                  "yrn42website-context"
  template:              "azure/aks-cluster"
  variables:
    clusterName:         "yrn42website-cluster"
    destinationContext:  "yrn42website-context"
    nodeResourceGroup:   "${env:resourceGroup}-aks"
