# Workloads information - azure
---
globalVariables:
  namespace:         "yrn42website-ns"
  resourceGroup:     "yrn42website-rg"
  containerPrefix:   "yrn42website-prefix"
  registryName:      "componentsRegistry"
  dockerUsername:    "placeholder"
  dockerPassword:    "placeholder"
  # TO-SET: set domain below, like yrn42.com
  # websiteDomain:     "yrn42website-domain"
  websiteDomain:     "yrn42.com"
  # TO-SET: set site address below, like www.yrn42.com
  # websiteHost:     "www.yrn42website-domain"
  websiteHost:       "www.yrn42.com"
  # TO-SET: set email address below, like certificates@yrn42.com
  # certManagerIssuerEmail: "certificates@yrn42website-domain"
  certManagerIssuerEmail: "certificates@yrn2.com"
  websiteTlsSecret:  "website-tls-secret"

workloads:
- context: "yrn42website-context"
  deployments:
  # Uninstall previous workloads: idempotent
  - kubectl: "delete namespace ${env:namespace} --v=1"
  - kubectl: "delete namespace cert-manager --v=1"
  - kubectl: "delete namespace ingress-basic --v=1"
  - kubectl: "delete -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml --v=1"
  - kubectl: "delete clusterrole nginx-ingress-ingress-nginx"
  - kubectl: "delete clusterrolebinding nginx-ingress-ingress-nginx"
  - shell: "Start-Sleep -s 9"
  # Install dependencies
  - kubectl: "create namespace ${env:namespace} --v=1"
  - kubectl: "create namespace cert-manager --v=1"
  - kubectl: "create namespace ingress-basic --v=1"
  - kubectl: "label namespace cert-manager certmanager.k8s.io/disable-validation=true --v=1"
  - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
  - helm: "repo add jetstack https://charts.jetstack.io"
  - helm: "repo update"
  - helm: "repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
  - helm: "repo update"
  - shell: "Start-Sleep -s 9"
  - helm: >
      install cert-manager jetstack/cert-manager
      --namespace cert-manager
      --version v1.1.0
      --set installCRDs=true
      --set nodeSelector."beta\.kubernetes\.io/os"=linux
      #--debug
  - helm: >
      install nginx-ingress ingress-nginx/ingress-nginx
      --namespace ingress-basic
      --set controller.replicaCount=2
      --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set controller.service.loadBalancerIP="$([Environment]::GetEnvironmentVariable("${env:contextName}.frontendIp"))"
      --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="${env:resourceGroup}.frontendIp"
      --set controller.admissionWebhooks.enabled=false
      #--debug
  # Wait for dependencies to be ready
  - shell: "Start-Sleep -s 9"
  # Install components
  - kubectl: "create secret docker-registry registry-credential --docker-server=http://$([Environment]::GetEnvironmentVariable(\"${env:registryName}.registryLocation\")) --docker-username=$(az acr credential show -n $([Environment]::GetEnvironmentVariable(\"${env:registryName}.registryLocation\")) --query username) --docker-password=$(az acr credential show -n $([Environment]::GetEnvironmentVariable(\"${env:registryName}.registryLocation\")) --query passwords[0].value) --v=1"
  - chart: "frontend/website"
    variables:
      installName: "yrn42website-install-website"