# Workloads information - azure
---
globalVariables:
  namespace:             "yrn42website-ns"
  resourceGroup:         "yrn42website-rg"
  containerPrefix:       "yrn42website-prefix"
  registryName:          "componentsRegistry"
  # TO-SET: set domain below, like yrn42.com
  # websiteDomain:         "yrn42website-domain"
  websiteDomain:         "yrn42.com"
  # TO-SET: set site address below, like www.yrn42.com
  # websiteHost:           "www.yrn42website-domain"
  websiteHost:           "www.yrn42.com"
  # TO-SET: set email address below, like certificates@yrn42.com
  # certManagerIssuerEmail: "certificates@yrn42website-domain"
  certManagerIssuerEmail: "certificates@yrn2.com"
  websiteTlsSecret:      "website-tls-secret"
  _registryLocation:     "$($([Environment]::GetEnvironmentVariable(\"${env:registryName}.registryLocation\")) -replace '.azurecr.io','')"
  dockerServer:          "http://${env:_registryLocation}.azurecr.io"
  dockerUsername:        "$(az acr credential show -n ${env:_registryLocation} --query username)"
  dockerPassword:        "$(az acr credential show -n ${env:_registryLocation} --query passwords[0].value)"
  ingressClass:          "nginx"

workloads:
- context: "yrn42website-context"
  variables:
    _hostname: "$([Environment]::GetEnvironmentVariable(\"${env:contextName}.hostname\"))"
    _frontendIp: "$([Environment]::GetEnvironmentVariable(\"${env:contextName}.frontendIp\"))"
  deployments:
  # Uninstall previous workloads: idempotent
  - kubectl: "delete namespace ${env:namespace} --v=1"
  - kubectl: "delete namespace cert-manager --v=1"
  - kubectl: "delete namespace ingress-basic --v=1"
  - kubectl: "delete -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml --v=1"
  - kubectl: "delete clusterrole nginx-ingress-ingress-nginx"
  - kubectl: "delete clusterrolebinding nginx-ingress-ingress-nginx"
  # Install dependencies
  - kubectl: "create namespace ${env:namespace} --v=1"
  - kubectl: "create namespace cert-manager --v=1"
  - kubectl: "create namespace ingress-basic --v=1"
  - kubectl: "label namespace cert-manager certmanager.k8s.io/disable-validation=true --v=1"
  - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
  - helm: "repo add jetstack https://charts.jetstack.io"
  - helm: "repo update"
  - helm: "repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
  - helm: "repo update"
  - helm: >
      install cert-manager jetstack/cert-manager
      --namespace cert-manager
      --version v1.1.0
      --set installCRDs=true
      --set nodeSelector."beta\.kubernetes\.io/os"=linux
      --debug
  - helm: >
      install nginx-ingress ingress-nginx/ingress-nginx
      --namespace ingress-basic
      --set controller.replicaCount=2
      --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set controller.admissionWebhooks.enabled=false
      --set controller.ingressClass=${env:ingressClass}
      --set controller.service.loadBalancerIP="${env:_frontendIp}"
      --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="${env:websiteHost}"
      --debug
  # Install components
  - kubectl: "create secret docker-registry registry-credential --docker-server=${env:dockerServer} --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
  - chart: "frontend/website"
    variables:
      installName: "yrn42website-install-website"
  - kubectl: "expose deployment/website"
  - shell: "Write-Information \">> Enpoint: https://${env:websiteHost}\""
  - shell: "Write-Information \">> Set DNS: ${env:websiteHost} -> ${env:_frontendIp}\""
  - shell: 'Write-Information "-- Waiting: kubectl wait --for=condition=Ready pods --all --all-namespaces"'
  - kubectl: "wait --for=condition=Ready pods --all --all-namespaces"
  - shell: 'Write-Information "-- Check containers started: kubectl get pods --all-namespaces"'
  - shell: "Write-Information \">>    Test: curl -v http://${env:_frontendIp} -H 'Host: ${env:websiteHost}'\""
