# Resources information - localhost
---
globalVariables:
  namespace:        "yrn42website-ns"
  clusterDnsPrefix: "yrn42website-dns"
  resourceGroup:    "yrn42website-rg"
  resourceTags:     "yrn42website-tags"
  nodeCount:        1
  registryName:     "componentsRegistry"

# Careful: if the template needs a veriable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
resources:
# localhost registry container
- name:             "componentsRegistry"
  template:         "localhost/registry"
  variables:
  
# localhost cluster reference
- name:             "yrn42website-context"
  template:         "localhost/context-copy"
  variables:
    clusterName:    "yrn42website-cluster"
    sourceContext:  "docker-desktop"
    destinationContext:  "yrn42website-context"
