apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-dir-pv
  labels:
    type: local
    app: dataload
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
  - ReadWriteMany 
  hostPath:
    # Note: after first time, if there is data in this folder...
    path: /data42
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-dir-pvc
  labels:
    app: dataload
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  volumeName: data-dir-pv