# Resources information - azure
---
globalVariables:
  namespace:             "yrn42peerkeys"
  clusterDnsPrefix:      "yrn42peerkeys"
  resourceGroup:         "yrn42peerkeys"
  # regions: az account list-locations -o table
  resourceRegion:        "westus2"
  resourceTags:          "yrn42peerkeys-tags"
  registryName:          "componentsRegistry"
  clusterVersion:        "1.20.2"
  nodeType:              "Standard_D2_v2"
  nodeCount:             3

resources:
# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
- name:                  "defaultResourceGroup"
  template:              "azure/resource-group"
  variables:

- name:                  "componentsRegistry"
  template:              "azure/registry"
  variables:
    # TO-SET: registry name must be globally unique
    uniqueName:          "yrn42peerkeys"

# 001 - southcentral us
- name:                  "rg001"
  template:              "azure/resource-group"
  variables:
    resourceGroup:       "yrn42peerkeys001"
    resourceRegion:      "southcentralus"

# {name}.hostname used in workloads
- name:                  "yrn42peerkeys001"
  template:              "azure/aks-cluster"
  variables:
    clusterName:         "yrn42peerkeys001"
    destinationContext:  "yrn42peerkeys001"
    resourceGroup:       "yrn42peerkeys001"
    resourceRegion:      "southcentralus"
    nodeResourceGroup:   "${env:resourceGroup}-aks"

# 002 - northeurope
- name:                  "rg002"
  template:              "azure/resource-group"
  variables:
    resourceGroup:       "yrn42peerkeys002"
    resourceRegion:      "northeurope"

# {name}.hostname used in workloads
- name:                  "yrn42peerkeys002"
  template:              "azure/aks-cluster"
  variables:
    clusterName:         "yrn42peerkeys002"
    destinationContext:  "yrn42peerkeys002"
    resourceGroup:       "yrn42peerkeys002"
    resourceRegion:      "northeurope"
    nodeResourceGroup:   "${env:resourceGroup}-aks"

# 003 - westus2
- name:                  "rg003"
  template:              "azure/resource-group"
  variables:
    resourceGroup:       "yrn42peerkeys003"
    resourceRegion:      "westus2"

# {name}.hostname used in workloads
- name:                  "yrn42peerkeys003"
  template:              "azure/aks-cluster"
  variables:
    clusterName:         "yrn42peerkeys003"
    destinationContext:  "yrn42peerkeys003"
    resourceGroup:       "yrn42peerkeys003"
    resourceRegion:      "westus2"
    nodeResourceGroup:   "${env:resourceGroup}-aks"
